[tool.black]
line-length = 88
target_version = ['py311']

[tool.ruff]
target-version = "py311"
ignore = [
    "E501",  # line too long, handled by black
    "E402",  # Imports should be at top
]

[tool.ruff.isort]
known-third-party = ["fastapi", "pydantic", "starlette"]

[tool.pyright]
ignore = [
    ".venv",
]
venvPath = "./.venv"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"

